### TEST ARTICLES
POST http://localhost:3000/posts
Content-Type: application/json

{"userId" : "674530947b8c3536d48433c7", "date" : "2024-11-24T10:30:00Z", "likes" : 1000, "title": "articulo9", "content" : "MimiblaBlablamiHolaHola"}


### 
GET http://localhost:3000/posts?pag=1

###
GET http://localhost:3000/posts?pag=2

### TEST COMMENTS
POST http://localhost:3000/comments
Content-Type: application/json

{"userId" : "674530947b8c3536d48433c7", "date" : "2024-11-24T10:30:00Z", "articleId" : "674531347b8c3536d48433d1", "content" : "commentario5"}

###
GET http://localhost:3000/comments?articleId=674531347b8c3536d48433d1

###
POST http://localhost:3000/users
Content-Type: application/json

{"email": "sergio.villa@iteso.mx", "firstname": "Sergio", "lastname": "Villa", "username": "user1", "password": "password"}


###
GET http://localhost:3000/users/auth?email=sergio.villa@iteso.mx&password=hola123